### ISSUE TITLE
Update API reference

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#1014]
We're getting quite a few errors / warnings when building the documentation. We need to go over the API reference and make sure all our public functions are documented there.

```python
Traceback (most recent call last):
  File ".../env/openenv_312/lib/python3.12/site-packages/sphinx/util/inspect.py", line 374, in safe_getattr
    return getattr(obj, name, *defargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'openghg.util' has no attribute 'convert_longitude'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".../env/openenv_312/lib/python3.12/site-packages/sphinx/ext/autodoc/importer.py", line 209, in import_object
    obj = attrgetter(obj, mangled_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../env/openenv_312/lib/python3.12/site-packages/sphinx/ext/autodoc/__init__.py", line 329, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../env/openenv_312/lib/python3.12/site-packages/sphinx/ext/autodoc/__init__.py", line 2844, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../env/openenv_312/lib/python3.12/site-packages/sphinx/util/inspect.py", line 390, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: convert_longitude

.../openghg/openghg/util/_domain.py:docstring of openghg.util._domain.find_domain:1: WARNING: duplicate object description of openghg.util.find_domain, other instance in api/api_util, use :no-index: for one of them
WARNING: autodoc: failed to import function 'load_emissions_database_parser' from module 'openghg.util'; the following exception was raised:
Traceback (most recent call last):
  File ".../env/openenv_312/lib/python3.12/site-packages/sphinx/util/inspect.py", line 374, in safe_getattr
    return getattr(obj, name, *defargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'openghg.util' has no attribute 'load_emissions_database_parser'. Did you mean: 'load_flux_database_parser'?
```

**Comment by rt17603** [comment]
We could do with running this to check whether these errors are still being produced.
