### ISSUE TITLE
error when trying to standardise footprints

### ISSUE THREAD

**Issue by alexdanjou** [openghg/openghg#1137]
### What is your issue?

For CBW, footprints in '/group/chem/acrg/object_stores/shared_store_zarr' only go back to 2004.
Footprints from 2000 (and even before) to 2004 are nonetheless present in '/group/chemistry/acrg/LPDM/fp_NAME/EUROPE'. 
I tried to standardise them but got an error. See below code an complete error message.

```
from glob import glob
from openghg.standardise._standardise import standardise_footprint

dir = f'/group/chemistry/acrg/LPDM/fp_NAME/EUROPE'
fooList = glob(f'{dir}/CBW-200magl/inert/CBW-200magl_EUROPE_200*.nc')

site,inlet = folder.split('/')[-2].split('-')

standardise_footprint(filepath=fooList,
                            site=site,
                            inlet=inlet,
                            model='NAME',
                            met_model='not_set',
                            domain='EUROPE',
                            species=species,
                            source_format='acrg_org',
                            if_exists='new',
                            store='shared_store_zarr',
                            continuous=False)
```

```
Traceback (most recent call last):
  File "timedeltas.pyx", line 732, in pandas._libs.tslibs.timedeltas.parse_timedelta_unit
KeyError: 'varies'
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/user/home/bq24992/workingDir/PARIS/Footprints/popFlexpartFootprints.py", line 32, in <module>
    standardise_footprint(filepath=fooList,
  File "/user/home/bq24992/openghg/openghg/standardise/_standardise.py", line 621, in standardise_footprint
    return standardise(
           ^^^^^^^^^^^^
  File "/user/home/bq24992/openghg/openghg/standardise/_standardise.py", line 51, in standardise
    result = dc.read_file(filepath=filepath, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/home/bq24992/openghg/openghg/store/_footprints.py", line 416, in read_file
    datasource_uuids = self.assign_data(
                       ^^^^^^^^^^^^^^^^^
  File "/user/home/bq24992/openghg/openghg/store/base/_base.py", line 367, in assign_data
    datasource.add_data(
  File "/user/home/bq24992/openghg/openghg/store/base/_datasource.py", line 155, in add_data
    return self.add_timed_data(
           ^^^^^^^^^^^^^^^^^^^^
  File "/user/home/bq24992/openghg/openghg/store/base/_datasource.py", line 208, in add_timed_data
    new_daterange_str = self.get_representative_daterange_str(dataset=data, period=period)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/home/bq24992/openghg/openghg/store/base/_datasource.py", line 503, in get_representative_daterange_str
    period_td = relative_time_offset(period=period)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/home/bq24992/openghg/openghg/util/_time.py", line 839, in relative_time_offset
    time_delta = time_offset(value, unit)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/home/bq24992/openghg/openghg/util/_time.py", line 798, in time_offset
    time_delta = Timedelta(value, unit)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "timedeltas.pyx", line 1895, in pandas._libs.tslibs.timedeltas.Timedelta.__new__
  File "timedeltas.pyx", line 734, in pandas._libs.tslibs.timedeltas.parse_timedelta_unit
ValueError: invalid unit abbreviation: varies
```

**Comment by alexdanjou** [comment]
When I process the files one by one, there is no issue and the footprint are standardise as expected.
```
from glob import glob
from openghg.standardise._standardise import standardise_footprint

dir = f'/group/chemistry/acrg/LPDM/fp_NAME/EUROPE'
fooList = glob(f'{dir}/CBW-200magl/inert/CBW-200magl_EUROPE_200*.nc')

site,inlet = folder.split('/')[-2].split('-')

for foo in fooList:
    standardise_footprint(filepath=foo,
                          site=site,
                          inlet=inlet,
                          model='NAME',
                          met_model='not_set',
                          domain='EUROPE',
                          species=species,
                          source_format='acrg_org',
                          if_exists='new',
                          store='shared_store_zarr',
                          continuous=False)
```
Thus the error described at first will not be reproductible as the footprints are now present..

**Comment by rt17603** [comment]
A small comment that including the `if_exists='new'` keyword will add these footprints as new version. This means that if there are already footprints from previous years these would no longer appear within the search as the latest version.

Did you find you needed to include that parameter? If so, it would be worth investigating why it was needed as it should work without it.

**Comment by alexdanjou** [comment]
Yes sorry about that, I realized after posting this. 
I used it when standardising FLEXPART data and forget to remove it when copy-pasting.

Hopefully I didn't rewrite to much stuff.. But not sure it was working though because I was getting a Warning saying something "Files already exist, will procees only 10 out of xxx"

**Comment by brendan-m-murphy** [comment]
I was able to add this data to a store with existing data by using `force=True`, `continuous=False`, and `period="1h"`. So, I think this is actually working, I'm not sure why I thought specifying the period didn't work. (See `/group/chem/acrg/brendan_zarr_stores/brendan_zarr_store1` for the results; v2 has all of the footprints for MHD from files without "UKV" in the file names.)

In this case the argument for `period` passed to `standardise_footprints` is used by the `acrg_org` parser. It's possible that there are some cases where `period` isn't used by some parsers.

So, we probably want a warning in this case, since we're overriding `period = "varies"` inferred by OpenGHG with `period = "1h"`. Also, a more helpful error message when trying to standardise with `period = "varies"` could help.

**Comment by rt17603** [comment]
Were we able to add a quick check for this and close this issue then? Perhaps the original data Alex tried to add could be used for this?

**Comment by alexdanjou** [comment]
I think this issue can be closed. The error message I get (with some other data though) is now more explicit (see below) and the issue is covered by #1151 which is also more to the point. Feel free to reopen it if you disagree.

```
ValueError: Continuous data with no
                             gaps is expected but no time period can
                             be inferred. Run with continuous=False
                             (and optionally specify period input)
                             to remove this constraint.
```
