### ISSUE TITLE
Unable to load in ICOS data for Macehead

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#57]
On Blue Pebble, if I attempt to load the ICOS data files for macehead this seems to process the files but these do not seem to be accessible within the object store 
```
from openghg.modules import ObsSurface
from pathlib import Path
import glob

sitename = "macehead"
sitecode="MHD"
icos_directory = Path(f"/work/chxmr/shared/obs_raw/AGAGE_GCWerks/data-icos/{sitename}/")

search_str = str(icos_directory / f"{sitecode.lower()}.*.1minute.*.dat")
icos_files = glob.glob(search_str)

mhd_results_4 = ObsSurface.read_file(filepath=icos_files, 
                                    data_type="ICOS", 
                                    site="MHD", network="ICOS")
```
![Loading_ICOS_data](https://user-images.githubusercontent.com/37222223/115590103-7f6de700-a2c8-11eb-9d7a-89dcf357daca.png)

When visualisting the object store this does not show the ICOS network
```
from openghg.objectstore import visualise_store
visualise_store()
```

When extracting obs_surface data this is to find any "co2" data for "mhd" (macehead) from the "ICOS" network
```
from openghg.localclient import get_obs_surface
data = get_obs_surface(site="mhd", species="co2", network="ICOS")
```

**Comment by rt17603** [comment]
Looks like this error is returned when trying to read the macehead icos data:
```
Traceback (most recent call last):
  File "/home/rt17603/openghg/openghg/modules/_obs_surface.py", line 142, in read_file
    measurement_type=measurement_type
  File "/home/rt17603/openghg/openghg/modules/_icos.py", line 46, in read_file
    gas_data = self.read_data(data_filepath=data_filepath, species=species, site=site)
  File "/home/rt17603/openghg/openghg/modules/_icos.py", line 111, in read_data
    date_parser=date_parser,
  File "/work/rt17603/environments/openghg/lib/python3.7/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/work/rt17603/environments/openghg/lib/python3.7/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/work/rt17603/environments/openghg/lib/python3.7/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/work/rt17603/environments/openghg/lib/python3.7/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/work/rt17603/environments/openghg/lib/python3.7/site-packages/pandas/io/parsers.py", line 1898, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 518, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 742, in pandas._libs.parsers.TextReader._get_header
ValueError: Passed header names mismatches usecols
```
