### ISSUE TITLE
Unable to retrieve time slice for flux data

### ISSUE THREAD

**Issue by rt17603** [openghg/openghg#996]
### What happened?

For data added to a new object store for the PARIS project the following error is returned when attempting to retrieve data from the `paris_store_zarr` on BP1 - `/group/chem/acrg/object_stores/paris/paris_store_zarr`.

```
File "/user/home/qq24644/.conda/envs/openghg_inv/lib/python3.12/site-packages/pandas/core/indexes/datetimes.py", line 632, in get_loc
    raise KeyError(orig_key) from err
KeyError: Timestamp('2018-12-31 23:59:58')
```

This was discovered when trying to run an inversion using openghg_inversions but can be replicated in openghg using the `get_flux` function and passing `start_date` and `end_date` inputs.

```
from openghg.retrieve import get_flux

flux = get_flux(species="c3f8", source="flat-annual-total", domain="EUROPE", store="paris_store_zarr").data
```
is able to retrieve the data but
```
flux = get_flux(species="c3f8", source="flat-annual-total", domain="EUROPE", store="paris_store_zarr", start_date="2018-01-01", end_date="2019-01-01").data
```
returns the same error as above.

### What did you expect to happen?

Data should be returned without error.

### Relevant log output

```Python
/user/home/qq24644/openghg_inversions/openghg_inversions/hbmcmc/inversion_pymc.py:408: SyntaxWarning: invalid escape sequence '\i'
  """
Traceback (most recent call last):
  File "index.pyx", line 609, in pandas._libs.index.DatetimeEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 2606, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 2630, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 1546300798000000000
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/user/home/qq24644/.conda/envs/openghg_inv/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 577, in pandas._libs.index.DatetimeEngine.get_loc
  File "index.pyx", line 611, in pandas._libs.index.DatetimeEngine.get_loc
KeyError: Timestamp('2018-12-31 23:59:58')
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
  File "/user/home/qq24644/.conda/envs/openghg_inv/lib/python3.12/site-packages/pandas/core/indexes/datetimes.py", line 630, in get_loc
    return Index.get_loc(self, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/home/qq24644/.conda/envs/openghg_inv/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: Timestamp('2018-12-31 23:59:58')
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
  File "/user/home/qq24644/openghg_inversions/openghg_inversions/hbmcmc/run_hbmcmc.py", line 247, in <module>
    mcmc_function(**param)
  File "/user/home/qq24644/openghg_inversions/openghg_inversions/hbmcmc/hbmcmc.py", line 406, in fixedbasisMCMC
    ) = get_data.data_processing_surface_notracer(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/home/qq24644/openghg_inversions/openghg_inversions/get_data.py", line 153, in data_processing_surface_notracer
    get_flux_data = get_flux(
                    ^^^^^^^^^
  File "/user/home/qq24644/.conda/envs/openghg_inv/lib/python3.12/site-packages/openghg/retrieve/_access.py", line 543, in get_flux
    em_data = _get_generic(
              ^^^^^^^^^^^^^
  File "/user/home/qq24644/.conda/envs/openghg_inv/lib/python3.12/site-packages/openghg/retrieve/_access.py", line 66, in _get_generic
    retrieved_data: Any = results.retrieve_all()
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/user/home/qq24644/.conda/envs/openghg_inv/lib/python3.12/site-packages/openghg/dataobjects/_searchresults.py", line 144, in retrieve_all
    return self._retrieve_by_uuid(uuids=self.metadata.keys(), version=version)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/home/qq24644/.conda/envs/openghg_inv/lib/python3.12/site-packages/openghg/dataobjects/_searchresults.py", line 212, in _retrieve_by_uuid
    ObsData(
  File "/user/home/qq24644/.conda/envs/openghg_inv/lib/python3.12/site-packages/openghg/dataobjects/_basedata.py", line 91, in __init__
    self.data = self.data.sel(time=slice(start_date, end_date))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/home/qq24644/.conda/envs/openghg_inv/lib/python3.12/site-packages/xarray/core/dataset.py", line 3097, in sel
    query_results = map_index_queries(
                    ^^^^^^^^^^^^^^^^^^
  File "/user/home/qq24644/.conda/envs/openghg_inv/lib/python3.12/site-packages/xarray/core/indexing.py", line 192, in map_index_queries
    results.append(index.sel(labels, **options))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/home/qq24644/.conda/envs/openghg_inv/lib/python3.12/site-packages/xarray/core/indexes.py", line 741, in sel
    indexer = _query_slice(self.index, label, coord_name, method, tolerance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/home/qq24644/.conda/envs/openghg_inv/lib/python3.12/site-packages/xarray/core/indexes.py", line 497, in _query_slice
    indexer = index.slice_indexer(
              ^^^^^^^^^^^^^^^^^^^^
  File "/user/home/qq24644/.conda/envs/openghg_inv/lib/python3.12/site-packages/pandas/core/indexes/datetimes.py", line 682, in slice_indexer
    return Index.slice_indexer(self, start, end, step)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/home/qq24644/.conda/envs/openghg_inv/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6662, in slice_indexer
    start_slice, end_slice = self.slice_locs(start, end, step=step)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/home/qq24644/.conda/envs/openghg_inv/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6885, in slice_locs
    end_slice = self.get_slice_bound(end, "right")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/home/qq24644/.conda/envs/openghg_inv/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6804, in get_slice_bound
    raise err
  File "/user/home/qq24644/.conda/envs/openghg_inv/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6798, in get_slice_bound
    slc = self.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^
  File "/user/home/qq24644/.conda/envs/openghg_inv/lib/python3.12/site-packages/pandas/core/indexes/datetimes.py", line 632, in get_loc
    raise KeyError(orig_key) from err
KeyError: Timestamp('2018-12-31 23:59:58')
```

### Anything else we need to know?

This should be set up to access the appropriate object store using
```
$ openghg --quickstart
```

### Environment

<details>
openghg 0.8.0

...
</details>

**Comment by rt17603** [comment]
From log output most relevant line seems to be:
```
File "/user/home/qq24644/.conda/envs/openghg_inv/lib/python3.12/site-packages/openghg/dataobjects/_basedata.py", line 91, in __init__
    self.data = self.data.sel(time=slice(start_date, end_date))
```

**Comment by rt17603** [comment]
The reason this seems to be giving the error is because the stored data is not sorted on the time dimension initially:
```
self.data.time
<xarray.DataArray 'time' (time: 6)> array(['2022-01-01T00:00:00.000000000', '2021-01-01T00:00:00.000000000',        '2019-01-01T00:00:00.000000000', '2018-01-01T00:00:00.000000000',        '2023-01-01T00:00:00.000000000', '2020-01-01T00:00:00.000000000'],       dtype='datetime64[ns]') Coordinates:   * time     (time) datetime64[ns] 2022-01-01 2021-01-01 ... 2020-01-01
```
There is code to sort by the time dimension but this is only called after the `self.data = self.data.sel(time=slice(start_date, end_date))` line causing the issue.

This needs to be fixed as it is valid to add data which is not sorted.
